env: dev

discord:
    adminIds:
        - YOUR_DISCORD_USER_ID
        - ANOTHER_DISCORD_USER_ID
    botToken: YOUR_DISCORD_BOT_TOKEN

gemini:
    apiKeys:
        - YOUR_GEMINI_API_KEY_1
        - YOUR_GEMINI_API_KEY_2
    apiModel: gemini-2.5-flash
    failDuration: 60000
    maxRetries: 3

supabase:
    url: https://YOUR_SUPABASE_PROJECT.supabase.co
    apiKey: sb_publishable_YOUR_SUPABASE_API_KEY

commands:
    admin:
        - add

currency:
    symbol: üê≥
    daily:
        minAmount: -1000
        maxAmount: 1000

game:
    baucua:
        minDuration: 10
        maxDuration: 60
        defaultDuration: 30
