env: dev

discord:
    ownerId: YOUR_DISCORD_ID
    botToken: YOUR_DISCORD_BOT_TOKEN

gemini:
    apiKeys:
        - GEMINI_API_KEY_1
        - GEMINI_API_KEY_2
        - GEMINI_API_KEY_3
    apiModel: gemini-2.5-flash
    failDuration: 60000
    maxRetries: 3

supabase:
    url: https://YOUR_SUPABASE_PROJECT.supabase.co
    apiKey: YOUR_SUPABASE_API_KEY
